name: RoyalChat
main: tk.royaldev.royalchat.RoyalChat
version: 0.0.6
website: http://dev.royaldev.org/
softdepend: [Vault, Towny, VanishNoPacket, Spout]
author: jkcclemens

commands:
  rchat:
    description: Display version number.
    usage: /<command>
    
  me:
    description: Allows you to emote.
    usage: /<command> <status>
    
  rclear:
    description: Clears the chat screen.
    aliases: [clear, clearscreen, cls]
    usage: /<command>

  say:
    description: Broadcasts a server message.
    aliases: [rsay]
    usage: /<command> [message]
    
permissions:
  rchat.*:
    description: Allows access to all RoyalChat commands.
    default: false
    children:
      rchat.rchat: true
      rchat.me: true
      rchat.clear: true
      rchat.say: true
      rchat.caps: true
  rchat.rchat:
    description: Allows you to reload RoyalChat.
    default: op
  rchat.me:
    description: Allows you to emote.
    default: op
  rchat.rclear:
    description: Allows you to clear the chat screen.
    default: op
  rchat.say:
    description: Allows you to broadcast a server message.
    default: op
  rchat.caps:
    description: Allows you to bypass the caps filter.
    default: op
    